# Generated by Django 4.0.4 on 2022-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
